/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddTokenModal: typeof import('./../components/web3/AddTokenModal.vue')['default']
    AppProvider: typeof import('./../components/common/app-provider.vue')['default']
    BetterScroll: typeof import('./../components/custom/better-scroll.vue')['default']
    BlockExplorer: typeof import('./../components/web3/BlockExplorer.vue')['default']
    ButtonIcon: typeof import('./../components/custom/button-icon.vue')['default']
    ContractCall: typeof import('./../components/web3/ContractCall.vue')['default']
    CountTo: typeof import('./../components/custom/count-to.vue')['default']
    DarkModeContainer: typeof import('./../components/common/dark-mode-container.vue')['default']
    DefiPortfolio: typeof import('./../components/web3/DefiPortfolio.vue')['default']
    EnsLookup: typeof import('./../components/web3/EnsLookup.vue')['default']
    ExceptionBase: typeof import('./../components/common/exception-base.vue')['default']
    FullScreen: typeof import('./../components/common/full-screen.vue')['default']
    IpfsUpload: typeof import('./../components/web3/IpfsUpload.vue')['default']
    LangSwitch: typeof import('./../components/common/lang-switch.vue')['default']
    LookForward: typeof import('./../components/custom/look-forward.vue')['default']
    MenuToggler: typeof import('./../components/common/menu-toggler.vue')['default']
    NFTGallery: typeof import('./../components/web3/NFTGallery.vue')['default']
    PinToggler: typeof import('./../components/common/pin-toggler.vue')['default']
    PortfolioDashboard: typeof import('./../components/web3/PortfolioDashboard.vue')['default']
    ReloadButton: typeof import('./../components/common/reload-button.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SoybeanAvatar: typeof import('./../components/custom/soybean-avatar.vue')['default']
    SvgIcon: typeof import('./../components/custom/svg-icon.vue')['default']
    SystemLogo: typeof import('./../components/common/system-logo.vue')['default']
    TableColumnSetting: typeof import('./../components/advanced/table-column-setting.vue')['default']
    TableHeaderOperation: typeof import('./../components/advanced/table-header-operation.vue')['default']
    ThemeSchemaSwitch: typeof import('./../components/common/theme-schema-switch.vue')['default']
    TokenSwap: typeof import('./../components/web3/TokenSwap.vue')['default']
    TransactionHistory: typeof import('./../components/web3/TransactionHistory.vue')['default']
    WalletConnect: typeof import('./../components/web3/WalletConnect.vue')['default']
    WaveBg: typeof import('./../components/custom/wave-bg.vue')['default']
  }
}
