/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "access-key": () => import("@/views/access-key/index.vue"),
  "dao-proposal-scanner": () => import("@/views/dao-proposal-scanner/index.vue"),
  home: () => import("@/views/home/index.vue"),
  log_login: () => import("@/views/log/login/index.vue"),
  log_operation: () => import("@/views/log/operation/index.vue"),
  manage_menu: () => import("@/views/manage/menu/index.vue"),
  manage_role: () => import("@/views/manage/role/index.vue"),
  "manage_user-detail": () => import("@/views/manage/user-detail/[id].vue"),
  manage_user: () => import("@/views/manage/user/index.vue"),
  web3_crosschainswapaggregator: () => import("@/views/web3/CrossChainSwapAggregator/index.vue"),
  web3_daotreasurymanager: () => import("@/views/web3/DaoTreasuryManager/index.vue"),
  web3_definews: () => import("@/views/web3/DefiNews/index.vue"),
  web3_domainservice: () => import("@/views/web3/DomainService/index.vue"),
  "web3_cross-chain-gas-station": () => import("@/views/web3/cross-chain-gas-station/index.vue"),
  "web3_defi-integration-hub": () => import("@/views/web3/defi-integration-hub/index.vue"),
  web3: () => import("@/views/web3/index.vue"),
  "web3_nft-floor-price-oracle": () => import("@/views/web3/nft-floor-price-oracle/index.vue"),
};
